swagger: "2.0"
info:
  description: API do sistema de telas do Ministério Público do Rio de Janeiro
  version: "1.0.0"
  title: Screen MPRJ
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /clima:
    get:
      operationId: model.clima.read
      tags:
        - Clima
      summary: BLANK
      description: BLANK
      responses:
        200:
          description: BLANK
          schema:
            properties:
              temperature:
                type: string

  /news:
    get:
      operationId: model.news.read
      tags:
        - news
      summary: Feed de notícias
      description: BLANK
      responses:
        200:
          description: BLANK
          schema:
            type: array
            items:
              properties:
                source:
                  type: string
                title:
                  type: string
                summary:
                  type: string
                href:
                  type: string
                published:
                  type: string
                published_parsed:
                  type: array
                  items:
                    type: integer

  /orgaos/financeiro/agrupado:
    get:
      operationId: model.orgaos.financeiro_agrupado
      parameters:
        - name: cdorg
          description: Código do órgão.
          in: query
          type: integer
          required: true
      tags:
      - Órgãos
      summary: Total dos vistas abertas no órgão
      description: Exibe a contagem de vistas abertas do órgão selecionado, agrupadas por tempo de abertura
      responses:
        200:
          description: Operação de contagem das vistas feita com sucesso
          schema:
            type: array
            items:
              properties:
                CONCESSIONARIAS:
                  type: integer
                IMOVEIS:
                  type: integer
                PESSOAL:
                  type: integer
                TERCEIRIZADOS:
                  type: integer