swagger: "2.0"
info:
  description: API do sistema de telas do Ministério Público do Rio de Janeiro
  version: "1.0.0"
  title: Screen MPRJ
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /orgaos:
    get:
      operationId: model.orgaos.list_orgaos
      tags:
        - Órgãos
      summary: Listagem dos órgãos
      description: Lista os órgãos do MPRJ, que forem acessíveis pelo sistema
      responses:
        200:
          description: Operação de listagem dos órgãos feita com sucesso
          schema:
            type: array
            items:
              properties:
                CDORG:
                  type: integer
                CRAAI:
                  type: string
                COMARCA:
                  type: string
                FORO:
                  type: string
                ORGAO:
                  type: string
                TITULAR:
                  type: string

  /orgaos/vistas:
    get:
      operationId: model.orgaos.list_vistas
      parameters:
        - name: cdorg
          description: Código do órgão.
          in: query
          type: integer
          required: true
      tags:
      - Órgãos
      summary: Listagem dos vistas abertas no órgão
      description: Lista as vistas abertas do órgão selecionado, agrupadas por tempo de abertura
      responses:
        200:
          description: Operação de listagem das vistas feita com sucesso
          schema:
            type: array
            items:
              properties:
                TOTAL:
                  type: integer
                HOJE:
                  type: integer
                ATE_30:
                  type: integer
                DE_30_A_40:
                  type: integer
                MAIS_40:
                  type: integer

  /orgaos/foto:
    get:
      operationId: model.orgaos.get_foto
      parameters:
        - name: cdmat
          description: Matricula.
          in: query
          type: integer
          required: true
      tags:
      - Órgãos
      summary: Foto do Membro
      description: Foto do Membro
      responses:
        200:
          description: Operação de listagem das vistas feita com sucesso
          schema:
            type: string
            items:
              properties:
                imagem:
                  type: string

  /orgaos/detalhes:
    get:
      operationId: model.orgaos.list_detalhes
      parameters:
        - name: cdorg
          description: Código do órgão.
          in: query
          type: integer
          required: true
      tags:
      - Órgãos
      summary: Detalhes dos órgãos
      description: Detalhes do órgão 
      responses:
        200:
          description: Operação de listagem das vistas feita com sucesso
          schema:
            type: array
            items:
              properties:
                TOTAL:
                  type: integer
                HOJE:
                  type: integer
                ATE_30:
                  type: integer
                DE_30_A_40:
                  type: integer
                MAIS_40:
                  type: integer

  /clima:
    get:
      operationId: model.clima.read
      tags:
        - Clima
      summary: BLANK
      description: BLANK
      responses:
        200:
          description: BLANK
          schema:
            properties:
              temperature:
                type: string

  /news:
    get:
      operationId: model.news.read
      tags:
        - news
      summary: Feed de notícias
      description: BLANK
      responses:
        200:
          description: BLANK
          schema:
            type: array
            items:
              properties:
                source:
                  type: string
                title:
                  type: string
                summary:
                  type: string
                href:
                  type: string
                published:
                  type: string
                published_parsed:
                  type: array
                  items:
                    type: integer